---
title: Jamie Wilkinson
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jamie@jamiedubs.com
description: "¯¯\\_(ツ)_/¯¯ I move away from the mic to breathe in\n"
baseurl: ''
url: https://www.jamiedubs.com
twitter_username: jamiew
github_username: jamiew
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-redirect-from
defaults:
  -
    values:
      layout: default
