---
title: jamiedubs.com - personal home page - Internet Scientist
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jamie@jamiedubs.com
description: "¯¯\\_(ツ)_/¯¯ I move away from the mic to move in\n"
baseurl: ''
url: http://www.jamiedubs.com
twitter_username: jamiew
github_username: jamiew
markdown: kramdown
plugins:
- jekyll-feed
