---
title: 58d95145c370d83db0430537
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
58d95145c370d83db0430537: "¯¯\\_(ツ)_/¯¯ I move away from the mic to move in\n"
baseurl: 
url: https://www.jamiedubs.com
twitter_username: jamiew
github_username: jamiew
markdown: kramdown
plugins:
- jekyll-feed
