---
title: Jamie Wilkinson
timezone: America/New_York
collections:
  posts:
    title: Blog posts
    output: true
email: jamie@jamiedubs.com
tagline: Technology & Internet culture
description: "I move away from the mic to breathe in"
baseurl: ''
url: https://jamiedubs.com
permalink: /blog/:title/
twitter_username: jamiew
github_username: jamiew
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-redirect-from
defaults:
  -
    values:
      layout: default
twitter:
  username: jamiew
  card: summary
logo: https://jamiedubs.com/images/mudkip_is_astounded3.png
